/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WordsImport } from './routes/words'
import { Route as SettingsImport } from './routes/settings'
import { Route as ProblemsImport } from './routes/problems'
import { Route as IndexImport } from './routes/index'
import { Route as WordsNewImport } from './routes/words_.new'
import { Route as WordsWordIdImport } from './routes/words_.$wordId'
import { Route as ProblemsProblemIdImport } from './routes/problems_.$problemId'

// Create/Update Routes

const WordsRoute = WordsImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ProblemsRoute = ProblemsImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WordsNewRoute = WordsNewImport.update({
  id: '/words_/new',
  path: '/words/new',
  getParentRoute: () => rootRoute,
} as any)

const WordsWordIdRoute = WordsWordIdImport.update({
  id: '/words_/$wordId',
  path: '/words/$wordId',
  getParentRoute: () => rootRoute,
} as any)

const ProblemsProblemIdRoute = ProblemsProblemIdImport.update({
  id: '/problems_/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsImport
      parentRoute: typeof rootRoute
    }
    '/problems_/$problemId': {
      id: '/problems_/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdImport
      parentRoute: typeof rootRoute
    }
    '/words_/$wordId': {
      id: '/words_/$wordId'
      path: '/words/$wordId'
      fullPath: '/words/$wordId'
      preLoaderRoute: typeof WordsWordIdImport
      parentRoute: typeof rootRoute
    }
    '/words_/new': {
      id: '/words_/new'
      path: '/words/new'
      fullPath: '/words/new'
      preLoaderRoute: typeof WordsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRoute
  '/settings': typeof SettingsRoute
  '/words': typeof WordsRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/words/$wordId': typeof WordsWordIdRoute
  '/words/new': typeof WordsNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRoute
  '/settings': typeof SettingsRoute
  '/words': typeof WordsRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/words/$wordId': typeof WordsWordIdRoute
  '/words/new': typeof WordsNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRoute
  '/settings': typeof SettingsRoute
  '/words': typeof WordsRoute
  '/problems_/$problemId': typeof ProblemsProblemIdRoute
  '/words_/$wordId': typeof WordsWordIdRoute
  '/words_/new': typeof WordsNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/problems'
    | '/settings'
    | '/words'
    | '/problems/$problemId'
    | '/words/$wordId'
    | '/words/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/problems'
    | '/settings'
    | '/words'
    | '/problems/$problemId'
    | '/words/$wordId'
    | '/words/new'
  id:
    | '__root__'
    | '/'
    | '/problems'
    | '/settings'
    | '/words'
    | '/problems_/$problemId'
    | '/words_/$wordId'
    | '/words_/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProblemsRoute: typeof ProblemsRoute
  SettingsRoute: typeof SettingsRoute
  WordsRoute: typeof WordsRoute
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  WordsWordIdRoute: typeof WordsWordIdRoute
  WordsNewRoute: typeof WordsNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProblemsRoute: ProblemsRoute,
  SettingsRoute: SettingsRoute,
  WordsRoute: WordsRoute,
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  WordsWordIdRoute: WordsWordIdRoute,
  WordsNewRoute: WordsNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/problems",
        "/settings",
        "/words",
        "/problems_/$problemId",
        "/words_/$wordId",
        "/words_/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/problems": {
      "filePath": "problems.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/words": {
      "filePath": "words.tsx"
    },
    "/problems_/$problemId": {
      "filePath": "problems_.$problemId.tsx"
    },
    "/words_/$wordId": {
      "filePath": "words_.$wordId.tsx"
    },
    "/words_/new": {
      "filePath": "words_.new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
