/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithStatusBarImport } from './routes/_with-status-bar'
import { Route as IndexImport } from './routes/index'
import { Route as WordsNewImport } from './routes/words_.new'
import { Route as WordsWordIdImport } from './routes/words_.$wordId'
import { Route as ProblemsProblemIdImport } from './routes/problems_.$problemId'
import { Route as WithStatusBarWordsImport } from './routes/_with-status-bar.words'
import { Route as WithStatusBarSettingsImport } from './routes/_with-status-bar.settings'
import { Route as WithStatusBarProblemsImport } from './routes/_with-status-bar.problems'

// Create/Update Routes

const WithStatusBarRoute = WithStatusBarImport.update({
  id: '/_with-status-bar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WordsNewRoute = WordsNewImport.update({
  id: '/words_/new',
  path: '/words/new',
  getParentRoute: () => rootRoute,
} as any)

const WordsWordIdRoute = WordsWordIdImport.update({
  id: '/words_/$wordId',
  path: '/words/$wordId',
  getParentRoute: () => rootRoute,
} as any)

const ProblemsProblemIdRoute = ProblemsProblemIdImport.update({
  id: '/problems_/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => rootRoute,
} as any)

const WithStatusBarWordsRoute = WithStatusBarWordsImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => WithStatusBarRoute,
} as any)

const WithStatusBarSettingsRoute = WithStatusBarSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WithStatusBarRoute,
} as any)

const WithStatusBarProblemsRoute = WithStatusBarProblemsImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => WithStatusBarRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_with-status-bar': {
      id: '/_with-status-bar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithStatusBarImport
      parentRoute: typeof rootRoute
    }
    '/_with-status-bar/problems': {
      id: '/_with-status-bar/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof WithStatusBarProblemsImport
      parentRoute: typeof WithStatusBarImport
    }
    '/_with-status-bar/settings': {
      id: '/_with-status-bar/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WithStatusBarSettingsImport
      parentRoute: typeof WithStatusBarImport
    }
    '/_with-status-bar/words': {
      id: '/_with-status-bar/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WithStatusBarWordsImport
      parentRoute: typeof WithStatusBarImport
    }
    '/problems_/$problemId': {
      id: '/problems_/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdImport
      parentRoute: typeof rootRoute
    }
    '/words_/$wordId': {
      id: '/words_/$wordId'
      path: '/words/$wordId'
      fullPath: '/words/$wordId'
      preLoaderRoute: typeof WordsWordIdImport
      parentRoute: typeof rootRoute
    }
    '/words_/new': {
      id: '/words_/new'
      path: '/words/new'
      fullPath: '/words/new'
      preLoaderRoute: typeof WordsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface WithStatusBarRouteChildren {
  WithStatusBarProblemsRoute: typeof WithStatusBarProblemsRoute
  WithStatusBarSettingsRoute: typeof WithStatusBarSettingsRoute
  WithStatusBarWordsRoute: typeof WithStatusBarWordsRoute
}

const WithStatusBarRouteChildren: WithStatusBarRouteChildren = {
  WithStatusBarProblemsRoute: WithStatusBarProblemsRoute,
  WithStatusBarSettingsRoute: WithStatusBarSettingsRoute,
  WithStatusBarWordsRoute: WithStatusBarWordsRoute,
}

const WithStatusBarRouteWithChildren = WithStatusBarRoute._addFileChildren(
  WithStatusBarRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof WithStatusBarRouteWithChildren
  '/problems': typeof WithStatusBarProblemsRoute
  '/settings': typeof WithStatusBarSettingsRoute
  '/words': typeof WithStatusBarWordsRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/words/$wordId': typeof WordsWordIdRoute
  '/words/new': typeof WordsNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof WithStatusBarRouteWithChildren
  '/problems': typeof WithStatusBarProblemsRoute
  '/settings': typeof WithStatusBarSettingsRoute
  '/words': typeof WithStatusBarWordsRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/words/$wordId': typeof WordsWordIdRoute
  '/words/new': typeof WordsNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_with-status-bar': typeof WithStatusBarRouteWithChildren
  '/_with-status-bar/problems': typeof WithStatusBarProblemsRoute
  '/_with-status-bar/settings': typeof WithStatusBarSettingsRoute
  '/_with-status-bar/words': typeof WithStatusBarWordsRoute
  '/problems_/$problemId': typeof ProblemsProblemIdRoute
  '/words_/$wordId': typeof WordsWordIdRoute
  '/words_/new': typeof WordsNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/problems'
    | '/settings'
    | '/words'
    | '/problems/$problemId'
    | '/words/$wordId'
    | '/words/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/problems'
    | '/settings'
    | '/words'
    | '/problems/$problemId'
    | '/words/$wordId'
    | '/words/new'
  id:
    | '__root__'
    | '/'
    | '/_with-status-bar'
    | '/_with-status-bar/problems'
    | '/_with-status-bar/settings'
    | '/_with-status-bar/words'
    | '/problems_/$problemId'
    | '/words_/$wordId'
    | '/words_/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithStatusBarRoute: typeof WithStatusBarRouteWithChildren
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  WordsWordIdRoute: typeof WordsWordIdRoute
  WordsNewRoute: typeof WordsNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithStatusBarRoute: WithStatusBarRouteWithChildren,
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  WordsWordIdRoute: WordsWordIdRoute,
  WordsNewRoute: WordsNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_with-status-bar",
        "/problems_/$problemId",
        "/words_/$wordId",
        "/words_/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_with-status-bar": {
      "filePath": "_with-status-bar.tsx",
      "children": [
        "/_with-status-bar/problems",
        "/_with-status-bar/settings",
        "/_with-status-bar/words"
      ]
    },
    "/_with-status-bar/problems": {
      "filePath": "_with-status-bar.problems.tsx",
      "parent": "/_with-status-bar"
    },
    "/_with-status-bar/settings": {
      "filePath": "_with-status-bar.settings.tsx",
      "parent": "/_with-status-bar"
    },
    "/_with-status-bar/words": {
      "filePath": "_with-status-bar.words.tsx",
      "parent": "/_with-status-bar"
    },
    "/problems_/$problemId": {
      "filePath": "problems_.$problemId.tsx"
    },
    "/words_/$wordId": {
      "filePath": "words_.$wordId.tsx"
    },
    "/words_/new": {
      "filePath": "words_.new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
